spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/Programming/h2/akkijang
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

image:
  dir: https://6cd9-14-39-127-17.ngrok-free.app/image/
upload:
  dir: /Users/jaemin/Desktop/workspace/project/akki-jang-be/akkijang/src/main/resources/static/image/
